import json
from typing import Dict, Any

def create_pdf_report(json_report_str: str) -> bytes:
    """
    STUB: In a real application, this function would take the final JSON
    report string generated by the agent, format it nicely (e.g., using 
    ReportLab or fpdf2) and return the PDF byte content.

    For now, it returns a readable byte string representation.
    """
    try:
        report_data: Dict[str, Any] = json.loads(json_report_str)
    except json.JSONDecodeError:
        # Handle cases where the LLM output is not perfect JSON
        return b"Error: Agent output was not valid JSON."

    # Format the opportunities list nicely
    opportunity_list = "\n"
    for opp in report_data.get('opportunities', []):
        opportunity_list += (
            f"  - Molecule: {opp.get('molecule_name', 'N/A')}\n"
            f"    Need Score: {opp.get('unmet_need_score', 'N/A')}/10\n"
            f"    Market Size: ${opp.get('market_size_usd', 'N/A')}M\n"
            f"    Phase: {opp.get('current_phase', 'N/A')}\n"
            f"    Patent Expiry: {opp.get('key_patent_expiry', 'N/A')}\n\n"
        )
    
    # Format the next steps list
    next_steps_list = "\n".join([f"  - {step}" for step in report_data.get('next_steps', [])])
    
    pdf_content = f"""
    PHARMA INNOVATION STRATEGY REPORT
    ====================================
    
    Query: {report_data.get('query', 'N/A')}
    Geography Focus: {report_data.get('target_geography', 'N/A')}
    
    EXECUTIVE SUMMARY
    -------------------
    {report_data.get('summary', 'No summary provided by the agent.')}
    
    TOP OPPORTUNITIES
    -------------------
    {opportunity_list.strip()}
    
    RECOMMENDED NEXT STEPS
    -----------------------
    {next_steps_list}
    """
    
    # Return bytes simulating a PDF
    return pdf_content.encode('utf-8')